In [13]:
import pandas as pd
import seaborn as sn

In [14]:
DP = pd.read_csv(r'D:\PROJECT\DYNAMITE\DATASET\Arjun\disease\Disease_Symptom_Prediction\dataset.csv')
DP2 = pd.read_csv(r'D:\PROJECT\DYNAMITE\DATASET\Arjun\disease\Disease_Symptom_Prediction\symptom_precaution.csv')
DP3 = pd.read_csv(r'D:\PROJECT\DYNAMITE\DATASET\Arjun\disease\Disease_Symptom_Prediction\Symptom-severity.csv')

In [15]:
DP.describe()

Disease  Symptom_1  Symptom_2 Symptom_3    Symptom_4  \
count               4920       4920       4920      4920         4572   
unique                41         34         48        54           50   
top     Fungal infection   vomiting   vomiting   fatigue   high_fever   
freq                 120        822        870       726          378   

        Symptom_5 Symptom_6        Symptom_7        Symptom_8  \
count        3714      2934             2268             1944   
unique         38        32               26               21   
top      headache    nausea   abdominal_pain   abdominal_pain   
freq          348       390              264              276   

                 Symptom_9          Symptom_10     Symptom_11 Symptom_12  \
count                 1692                1512           1194        744   
unique                  22                  21             18         11   
top      yellowing_of_eyes   yellowing_of_eyes   irritability    malaise   
freq                   228                 198            120        126   

          Symptom_13   Symptom_14   Symptom_15        Symptom_16    Symptom_17  
count            504          306          240               192            72  
unique             8            4            3                 3             1  
top      muscle_pain   chest_pain   chest_pain   blood_in_sputum   muscle_pain  
freq              72           96          144                72            72

In [16]:
DP.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Data columns (total 18 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Disease     4920 non-null   object
 1   Symptom_1   4920 non-null   object
 2   Symptom_2   4920 non-null   object
 3   Symptom_3   4920 non-null   object
 4   Symptom_4   4572 non-null   object
 5   Symptom_5   3714 non-null   object
 6   Symptom_6   2934 non-null   object
 7   Symptom_7   2268 non-null   object
 8   Symptom_8   1944 non-null   object
 9   Symptom_9   1692 non-null   object
 10  Symptom_10  1512 non-null   object
 11  Symptom_11  1194 non-null   object
 12  Symptom_12  744 non-null    object
 13  Symptom_13  504 non-null    object
 14  Symptom_14  306 non-null    object
 15  Symptom_15  240 non-null    object
 16  Symptom_16  192 non-null    object
 17  Symptom_17  72 non-null     object
dtypes: object(18)
memory usage: 692.0+ KB


In [17]:
DP.isna().sum()
DP.isnull().sum()

cols = DP.columns
data = DP[cols].values.flatten()

s = pd.Series(data)
s = s.str.strip()
s = s.values.reshape(DP.shape)

DP = pd.DataFrame(s, columns=DP.columns)

DP = DP.fillna(0)
DP.head()

Disease  Symptom_1             Symptom_2             Symptom_3  \
0  Fungal infection    itching             skin_rash  nodal_skin_eruptions   
1  Fungal infection  skin_rash  nodal_skin_eruptions   dischromic _patches   
2  Fungal infection    itching  nodal_skin_eruptions   dischromic _patches   
3  Fungal infection    itching             skin_rash   dischromic _patches   
4  Fungal infection    itching             skin_rash  nodal_skin_eruptions   

             Symptom_4 Symptom_5 Symptom_6 Symptom_7 Symptom_8 Symptom_9  \
0  dischromic _patches         0         0         0         0         0   
1                    0         0         0         0         0         0   
2                    0         0         0         0         0         0   
3                    0         0         0         0         0         0   
4                    0         0         0         0         0         0   

  Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14 Symptom_15  \
0          0          0          0          0          0          0   
1          0          0          0          0          0          0   
2          0          0          0          0          0          0   
3          0          0          0          0          0          0   
4          0          0          0          0          0          0   

  Symptom_16 Symptom_17  
0          0          0  
1          0          0  
2          0          0  
3          0          0  
4          0          0

In [18]:
DP.head(100)

Disease  Symptom_1             Symptom_2             Symptom_3  \
0   Fungal infection    itching             skin_rash  nodal_skin_eruptions   
1   Fungal infection  skin_rash  nodal_skin_eruptions   dischromic _patches   
2   Fungal infection    itching  nodal_skin_eruptions   dischromic _patches   
3   Fungal infection    itching             skin_rash   dischromic _patches   
4   Fungal infection    itching             skin_rash  nodal_skin_eruptions   
..               ...        ...                   ...                   ...   
95  Bronchial Asthma    fatigue                 cough            high_fever   
96  Bronchial Asthma    fatigue                 cough            high_fever   
97  Bronchial Asthma    fatigue                 cough            high_fever   
98  Bronchial Asthma      cough            high_fever        breathlessness   
99  Bronchial Asthma    fatigue            high_fever        breathlessness   

              Symptom_4       Symptom_5      Symptom_6 Symptom_7 Symptom_8  \
0   dischromic _patches               0              0         0         0   
1                     0               0              0         0         0   
2                     0               0              0         0         0   
3                     0               0              0         0         0   
4                     0               0              0         0         0   
..                  ...             ...            ...       ...       ...   
95       breathlessness   mucoid_sputum              0         0         0   
96       breathlessness  family_history              0         0         0   
97       breathlessness  family_history  mucoid_sputum         0         0   
98       family_history   mucoid_sputum              0         0         0   
99       family_history   mucoid_sputum              0         0         0   

   Symptom_9 Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14  \
0          0          0          0          0          0          0   
1          0          0          0          0          0          0   
2          0          0          0          0          0          0   
3          0          0          0          0          0          0   
4          0          0          0          0          0          0   
..       ...        ...        ...        ...        ...        ...   
95         0          0          0          0          0          0   
96         0          0          0          0          0          0   
97         0          0          0          0          0          0   
98         0          0          0          0          0          0   
99         0          0          0          0          0          0   

   Symptom_15 Symptom_16 Symptom_17  
0           0          0          0  
1           0          0          0  
2           0          0          0  
3           0          0          0  
4           0          0          0  
..        ...        ...        ...  
95          0          0          0  
96          0          0          0  
97          0          0          0  
98          0          0          0  
99          0          0          0  

[100 rows x 18 columns]

In [19]:
colm = DP.columns
dataset_edit = DP[colm].values.flatten()

In [20]:
print(dataset_edit)

['Fungal infection' 'itching' 'skin_rash' ... 0 0 0]


In [21]:
sample = pd.Series(dataset_edit)
sample = sample.str.strip().values.reshape(DP.shape)
# sample = sample.values.reshape(DP.shape)



In [22]:
DP4 = pd.DataFrame(sample, columns=DP.columns)
DP4.head()

Disease  Symptom_1             Symptom_2             Symptom_3  \
0  Fungal infection    itching             skin_rash  nodal_skin_eruptions   
1  Fungal infection  skin_rash  nodal_skin_eruptions   dischromic _patches   
2  Fungal infection    itching  nodal_skin_eruptions   dischromic _patches   
3  Fungal infection    itching             skin_rash   dischromic _patches   
4  Fungal infection    itching             skin_rash  nodal_skin_eruptions   

             Symptom_4 Symptom_5 Symptom_6 Symptom_7 Symptom_8 Symptom_9  \
0  dischromic _patches       NaN       NaN       NaN       NaN       NaN   
1                  NaN       NaN       NaN       NaN       NaN       NaN   
2                  NaN       NaN       NaN       NaN       NaN       NaN   
3                  NaN       NaN       NaN       NaN       NaN       NaN   
4                  NaN       NaN       NaN       NaN       NaN       NaN   

  Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14 Symptom_15  \
0        NaN        NaN        NaN        NaN        NaN        NaN   
1        NaN        NaN        NaN        NaN        NaN        NaN   
2        NaN        NaN        NaN        NaN        NaN        NaN   
3        NaN        NaN        NaN        NaN        NaN        NaN   
4        NaN        NaN        NaN        NaN        NaN        NaN   

  Symptom_16 Symptom_17  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [23]:
sample_vals = DP.values
# print(sample_vals)
# symptoms = DP3['']

In [24]:
DP3.head(10)

Symptom  weight
0               itching       1
1             skin_rash       3
2  nodal_skin_eruptions       4
3   continuous_sneezing       4
4             shivering       5
5                chills       3
6            joint_pain       3
7          stomach_pain       5
8               acidity       3
9      ulcers_on_tongue       4

In [25]:
# DP3.count()
vals = DP.values
symptoms = DP3['Symptom'].unique()

for i in range(len(symptoms)):
    vals[vals == symptoms[i]] = DP3[DP3['Symptom'] == symptoms[i]]['weight'].values[0]
    
d = pd.DataFrame(vals,columns=DP.columns)

In [26]:
print(symptoms)
with open('sample.txt', 'w+') as f:
    f.write(str(symptoms))

['itching' 'skin_rash' 'nodal_skin_eruptions' 'continuous_sneezing'
 'shivering' 'chills' 'joint_pain' 'stomach_pain' 'acidity'
 'ulcers_on_tongue' 'muscle_wasting' 'vomiting' 'burning_micturition'
 'spotting_urination' 'fatigue' 'weight_gain' 'anxiety'
 'cold_hands_and_feets' 'mood_swings' 'weight_loss' 'restlessness'
 'lethargy' 'patches_in_throat' 'irregular_sugar_level' 'cough'
 'high_fever' 'sunken_eyes' 'breathlessness' 'sweating' 'dehydration'
 'indigestion' 'headache' 'yellowish_skin' 'dark_urine' 'nausea'
 'loss_of_appetite' 'pain_behind_the_eyes' 'back_pain' 'constipation'
 'abdominal_pain' 'diarrhoea' 'mild_fever' 'yellow_urine'
 'yellowing_of_eyes' 'acute_liver_failure' 'fluid_overload'
 'swelling_of_stomach' 'swelled_lymph_nodes' 'malaise'
 'blurred_and_distorted_vision' 'phlegm' 'throat_irritation'
 'redness_of_eyes' 'sinus_pressure' 'runny_nose' 'congestion' 'chest_pain'
 'weakness_in_limbs' 'fast_heart_rate' 'pain_during_bowel_movements'
 'pain_in_anal_region' 'bloody_s

In [27]:
d = d.replace('dischromic _patches',0)
d = d.replace('spotting_ urination',0)
DP = d.replace('foul_smell_of urine',0)
DP.head(20)

Disease  Symptom_1  Symptom_2  Symptom_3  Symptom_4  Symptom_5  \
0   Fungal infection          1          3          4          0          0   
1   Fungal infection          3          4          0          0          0   
2   Fungal infection          1          4          0          0          0   
3   Fungal infection          1          3          0          0          0   
4   Fungal infection          1          3          4          0          0   
5   Fungal infection          3          4          0          0          0   
6   Fungal infection          1          4          0          0          0   
7   Fungal infection          1          3          0          0          0   
8   Fungal infection          1          3          4          0          0   
9   Fungal infection          1          3          4          0          0   
10           Allergy          4          5          3          4          0   
11           Allergy          5          3          4          0          0   
12           Allergy          4          3          4          0          0   
13           Allergy          4          5          4          0          0   
14           Allergy          4          5          3          0          0   
15           Allergy          5          3          4          0          0   
16           Allergy          4          3          4          0          0   
17           Allergy          4          5          4          0          0   
18           Allergy          4          5          3          0          0   
19           Allergy          4          5          3          4          0   

    Symptom_6  Symptom_7  Symptom_8  Symptom_9  Symptom_10  Symptom_11  \
0           0          0          0          0           0           0   
1           0          0          0          0           0           0   
2           0          0          0          0           0           0   
3           0          0          0          0           0           0   
4           0          0          0          0           0           0   
5           0          0          0          0           0           0   
6           0          0          0          0           0           0   
7           0          0          0          0           0           0   
8           0          0          0          0           0           0   
9           0          0          0          0           0           0   
10          0          0          0          0           0           0   
11          0          0          0          0           0           0   
12          0          0          0          0           0           0   
13          0          0          0          0           0           0   
14          0          0          0          0           0           0   
15          0          0          0          0           0           0   
16          0          0          0          0           0           0   
17          0          0          0          0           0           0   
18          0          0          0          0           0           0   
19          0          0          0          0           0           0   

    Symptom_12  Symptom_13  Symptom_14  Symptom_15  Symptom_16  Symptom_17  
0            0           0           0           0           0           0  
1            0           0           0           0           0           0  
2            0           0           0           0           0           0  
3            0           0           0           0           0           0  
4            0           0           0           0           0           0  
5            0           0           0           0           0           0  
6            0           0           0           0           0           0  
7            0           0           0           0           0           0  
8            0           0           0           0           0           0  
9            0           0  

In [28]:
DP.values

array([['Fungal infection', 1, 3, ..., 0, 0, 0],
       ['Fungal infection', 3, 4, ..., 0, 0, 0],
       ['Fungal infection', 1, 4, ..., 0, 0, 0],
       ...,
       ['Urinary tract infection', 6, 4, ..., 0, 0, 0],
       ['Psoriasis', 3, 3, ..., 0, 0, 0],
       ['Impetigo', 3, 7, ..., 0, 0, 0]], dtype=object)

In [29]:
(DP[cols] == 0).all()

DP['Disease'].value_counts()

DP['Disease'].unique()

data = DP.iloc[:,1:].values
labels = DP['Disease'].values

In [30]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import f1_score, accuracy_score, confusion_matrix
import seaborn as sns


In [31]:
x_train, x_test, y_train, y_test = train_test_split(data, labels, shuffle=True, train_size = 0.85)
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(4182, 17) (738, 17) (4182,) (738,)


In [32]:
print(data)

[[1 3 4 ... 0 0 0]
 [3 4 0 ... 0 0 0]
 [1 4 0 ... 0 0 0]
 ...
 [6 4 0 ... 0 0 0]
 [3 3 3 ... 0 0 0]
 [3 7 4 ... 0 0 0]]


In [33]:
model = SVC()
model.fit(x_train, y_train)

preds = model.predict(x_test)
print(preds)

['Acne' 'Malaria' 'Typhoid' 'Impetigo' 'Cervical spondylosis'
 'Heart attack' 'Hepatitis C' 'Dimorphic hemmorhoids(piles)' 'Diabetes'
 'Osteoarthristis' 'Hypoglycemia' 'Varicose veins' 'Allergy'
 'Osteoarthristis' 'Hepatitis C' '(vertigo) Paroymsal  Positional Vertigo'
 'Gastroenteritis' 'Hepatitis B' '(vertigo) Paroymsal  Positional Vertigo'
 'GERD' 'Hyperthyroidism' 'Paralysis (brain hemorrhage)' 'Hepatitis B'
 'GERD' 'Acne' 'Migraine' 'Paralysis (brain hemorrhage)' 'Hypertension'
 'Chronic cholestasis' 'Hepatitis E' 'Dimorphic hemmorhoids(piles)'
 'Hepatitis C' 'AIDS' 'Alcoholic hepatitis' 'Urinary tract infection'
 'Hepatitis E' 'Chicken pox' 'Chicken pox' 'Fungal infection' 'Arthritis'
 'Dengue' 'Migraine' 'Urinary tract infection' 'Bronchial Asthma'
 'hepatitis A' 'Acne' '(vertigo) Paroymsal  Positional Vertigo'
 'Hepatitis D' 'Chicken pox' 'Hepatitis E' 'Bronchial Asthma'
 'Fungal infection' 'Malaria' 'Psoriasis' 'Jaundice'
 'Dimorphic hemmorhoids(piles)' 'Cervical spondylosis' 

In [34]:
import pickle
pickle.dump(model, open(r'D:\PROJECT\DYNAMITE\SAVED_MODEL\disease_model.sav','wb'))